"""CLI entrypoint: render the written EDA analysis as a self-contained HTML
artefact (reports/eda/EDA_ANALYSIS.html), in the same shared design system as
the 6 generated dashboards.

The narrative content below is authored, not auto-generated from the data --
but every number in it was sourced by re-running src/eda/compute_stats.py
against the live parquet files (see the "Source" line) and cross-checked
against src/dax/features/add_missingness_flags.py and
claude/passive-defense-data-exploration-context.md for the nearest_defender_distance
bug-fix history. Regenerate this file whenever the underlying analysis is
re-verified against a fresh feature build; do not hand-edit the HTML output.

Usage:
    python -m src.eda.generate_analysis_report
"""

from __future__ import annotations

from pathlib import Path

import markdown

from src.eda import render

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "reports" / "eda" / "EDA_ANALYSIS.html"

SOURCE_NOTE = (
    "Source: `reports/eda/*.html` (generated by `python -m src.eda.generate_reports --dataset all`, "
    "reading `data/features/player_defensive_actions.parquet` and `data/features/passive_defense.parquet`). "
    "Every number below traces to those generated outputs or to a direct re-run of `src/eda/compute_stats.py` "
    "against the same parquet files."
)

BOTTOM_LINE = (
    "Both datasets show the same dominant signal: **proximity to either box** (`is_in_defending_box`, "
    "`is_in_attacking_box`) and **phase** (`box_defence`, `high_press_proxy`) are associated with roughly "
    "double the base shot rate, consistently across active and passive tables. The active dataset's "
    "distance/count features are usable again after a real bug fix -- `nearest_defender_distance` and its "
    "correlated siblings were previously self-referencing the acting player (fixed; verified 0.0% residual). "
    "Camera-coverage metadata is excluded outright because it correlates with shots for a reason that has "
    "nothing to do with defending. After every exclusion, 51 active and 44 passive candidate features remain, "
    "unpruned for redundancy -- that's the next pass."
)

ANALYSIS_MARKDOWN = f"""{SOURCE_NOTE}

## Bottom line up front

{BOTTOM_LINE}

## 1. Overview

| | `player_defensive_actions.parquet` (active) | `passive_defense.parquet` (passive) |
|---|---|---|
| Grain | one row per actual defensive action | one row per visible defender-slot per on-ball attacking event |
| Rows | 56,068 | 1,593,181 |
| Base rate (`target_future_shot_10s` mean) | 7.79% | 5.97% |

The two tables are modelled separately because their grains are disjoint and not nestable: the active table has one row per thing a defender actually did, while the passive table has one row per defender who was merely *present* (possibly doing nothing) for every visible on-ball attacking event -- a single active action can correspond to zero, one, or several passive rows for teammates who weren't the actor. Pooling them would double-count positioning context and conflate "did something" with "was positioned somewhere."

## 2. Methodology

- **Categorical shot rate**: `df.groupby(col)['target_future_shot_10s'].agg(n='count', shots='sum', rate=lambda s: s.mean()*100)` -- always a groupby-mean against the full row population per category, never filter-to-shots-then-distribute.
- **Boolean lift**: `rate_true - rate_false` in percentage points, where each rate is `df.loc[df[col]==True/False, target].mean()*100`. `pct_true = df[col].mean()*100`. Any True or False group with n < 500 is flagged small-n, not excluded.
- **Continuous distributions**: 24 equal-width bins from the column min to its 99th percentile (`np.percentile(x, 99)`); rows above p99 are counted as `n_extreme` and reported with the true max, never dropped from the histogram population or from `mean`/`median`/`skew` (`scipy.stats.skew`), which are computed on the full unclipped column.
- **Discrete distributions**: raw value counts capped at 20 distinct values, tail bucketed beyond that.

Every relationship in this report is a correlation or association, never a cause -- that includes every header, table caption and finding below, with no exceptions.

## 3. Findings by dataset

### 3.1 Active (`player_defensive_actions.parquet`, n=56,068, base rate 7.79%)

#### Strongest categorical correlates

| Column | Top categories (rate, n) |
|---|---|
| `play_pattern` | From Counter 21.01% (n=752); From Corner 19.97% (n=3,090); From Free Kick 9.11% (n=8,093) |
| `phase_label_prev_event` | box_defence 17.21% (n=6,887); high_press_proxy 15.28% (n=9,701); settled_low_block_proxy 6.39% (n=5,762) |
| `phase_label` | box_defence 15.87% (n=9,144); high_press_proxy 15.24% (n=9,094); transition_defence 5.98% (n=5,699) |
| `action_zone` | attacking_third_center 15.19% (n=11,309); defensive_third_center 15.10% (n=9,509); defensive_third_left_flank 5.03% (n=3,458) |
| `position` | Left Center Back 11.50% (n=4,619); Center Back 11.45% (n=1,424); Right Center Back 10.19% (n=4,545) |

`play_pattern = From Counter` is the single largest divergence from base rate anywhere in the categorical set (+13.22pp on n=752).

#### Strongest boolean correlates

| Column | Lift | True rate (n) | False rate (n) | % True |
|---|---|---|---|---|
| `is_in_defending_box` | **+12.04pp** | 18.79% (4,842) | 6.75% (51,226) | 8.6% |
| `is_in_attacking_box` | **+11.99pp** | 18.52% (5,886) | 6.53% (50,182) | 10.5% |
| `is_central_lane` | +8.07pp | 12.35% (24,356) | 4.29% (31,712) | 43.4% |
| `is_high_zone` | +7.22pp | 13.27% (13,516) | 6.05% (42,552) | 24.1% |
| `is_deep_zone` | +7.22pp | 13.54% (11,441) | 6.32% (44,627) | 20.4% |
| `is_wide_lane` | **-7.24pp** | 2.54% (15,406) | 9.78% (40,662) | 27.5% |
| `counterpress` | -4.40pp | 4.07% (8,690) | 8.47% (47,378) | 15.5% |

Small-n caution (False-group n < 500, lift unstable):

- `has_visible_attacker`: False n=**31** -- below the n<500 threshold, flagged small-n; the +4.57pp lift is not trustworthy.
- `has_visible_defender`: False n=**76** -- below the threshold, flagged small-n; the +3.85pp lift is not trustworthy.
- `has_previous_event`: False n=**4,534** -- above the threshold, not flagged small-n; its +6.39pp lift is trustworthy at that sample size, listed here only because it shares the same "structural absence" cause as the two above (first event of a possession has no prior event to look back at).

#### Numerical shape

Heavily skewed (need a log/rank transform before linear methods):

| Column | skew | mean | median |
|---|---|---|---|
| `nearest_attacker_distance` | 4.63 | 7.08 | 3.20 |
| `nearest_defender_distance` | 4.38 | 9.49 | 6.35 |
| `attacker_defender_ratio` | 3.27 | 1.00 | 0.89 |
| `possession_elapsed_seconds` | 2.26 | 18.65 | 11.00 |

Well-behaved (skew within ~±0.25 of zero): `attacker_spread`, `defender_spread`, `attacker_centroid_x/y`, `defender_centroid_x/y`, `distance_to_defending_box`, `distance_to_attacking_box`, `distance_to_defending_goal`, `distance_to_attacking_goal`, `distance_to_center_line`, `attacking_goal_centrality`, `match_time_seconds`.

#### The `nearest_defender_distance` self-reference bug

StatsBomb 360 freeze frames include the acting player's own position, marked `"actor": true`. Before the fix, `_support_features` in `src/dax/features/player_defense.py` treated that entry as an ordinary support player, so a defender's distance to their own action was measured as their distance to themselves -- `nearest_defender_distance` was effectively ~0m in **73.6%** of rows. The same root cause, via the attacker branch of the same freeze-frame split, produced the identical pattern in `nearest_attacker_distance` for **20.0%** of rows (`Ball Recovery`/`Interception` events where the recovering player is on the attacking side).

Fix: `_exclude_actor_from_frame` now strips the `actor: true` entry before the attacker/defender split, for every column built from that candidate pool -- `nearest_attacker_distance`/`nearest_defender_distance`, `attacker_centroid_x/y`/`defender_centroid_x/y`, `attacker_spread`/`defender_spread`, `visible_attacker_count`/`visible_defender_count`, `attackers_within_5m/10m`/`defenders_within_5m/10m`, `local_numerical_balance_5m/10m`, `attacker_defender_ratio`, `defenders_between_ball_and_attacking_goal`.

Verified fixed, directly against the current parquet:

- Rows with `nearest_defender_distance` < 0.01m: **0 of 56,068 (0.0%)**, down from 73.6%.
- Rows with `nearest_attacker_distance` < 0.01m: **0 of 56,068 (0.0%)**, down from 20.0%.
- `nearest_defender_distance` now has mean **9.49m**, median **6.35m**, skew **4.38** -- right-skewed but consistent with genuine on-pitch spacing, not a ~0m spike.

`defender_centroid_x/y` and `defender_spread` (and their attacker-side counterparts) were built from the same corrected candidate pool and checked directly: `defender_centroid_x` ranges 0.04-119.10 with no near-zero clustering, and the 244 rows where `defender_spread == 0.0` (198 for `attacker_spread`) are single-visible-defender/attacker frames where a spread of zero is the correct value, not a residual self-reference artifact -- cleared.

### 3.2 Passive (`passive_defense.parquet`, n=1,593,181, base rate 5.97%)

#### Strongest categorical correlates

| Column | Top categories (rate, n) |
|---|---|
| `phase_label` | high_press_proxy 14.79% (n=197,765); box_defence 14.06% (n=103,445); settled_low_block_proxy 5.58% (n=218,035) |
| `defender_zone` | attacking_third_center 9.87% (n=258,246); defensive_third_center 9.70% (n=403,528); attacking_third_right_flank 6.07% (n=44,089) |
| `on_ball_event_type` | Dribble 11.12% (n=21,436); Shot 7.09% (n=24,496); Carry 6.13% (n=714,233) |
| `defender_functional_role` | unclassified 6.28% (n=994,663); central_screen 5.76% (n=213,043); last_line 5.70% (n=216,551) |

#### Strongest boolean correlates

| Column | Lift | True rate (n) | False rate (n) | % True |
|---|---|---|---|---|
| `is_in_defending_box` | **+12.31pp** | 17.39% (114,367) | 5.08% (1,478,814) | 7.2% |
| `is_in_attacking_box` | **+11.85pp** | 17.26% (74,676) | 5.41% (1,518,505) | 4.7% |
| `is_deep_zone` | +7.02pp | 11.53% (330,258) | 4.51% (1,262,923) | 20.7% |
| `is_high_zone` | +6.41pp | 11.51% (214,364) | 5.10% (1,378,817) | 13.5% |
| `has_option_3` | **-9.18pp** | 5.95% (1,591,000) | 15.13% (2,181) | 99.9% |
| `has_option_2` | -8.73pp | 5.96% (1,592,902) | 14.70% (279) | 100.0% |
| `is_wide_lane` | -2.76pp | 3.49% (165,072) | 6.25% (1,428,109) | 10.4% |

Small-n caution, explicit false-group sizes as requested:

- `has_option_2`: False n=**279** -- below the n<500 threshold, flagged small-n; the -8.73pp lift is the least trustworthy number in this table.
- `has_option_3`: False n=**2,181** -- above the threshold, not flagged, but still a structurally rare group (fewer than 3 attackers were visible to rank).
- `has_screened_outcome`: False n=**2,581** -- above the threshold; lift +5.47pp (True 5.97% vs False 0.50%), driven by the same "no next event existed" rarity.

#### Numerical shape

Heavily skewed:

| Column | skew | mean | median |
|---|---|---|---|
| `zone_defensive_value` | 8.18 | 0.024 | 0.017 |
| `top_option_1_threat_score` | 7.91 | 0.022 | 0.016 |
| `lane_screening_score_option_1` | 3.11 | 0.114 | 0.065 |
| `lane_screening_score_option_2` | 3.07 | 0.114 | 0.064 |
| `lane_screening_score_option_3` | 2.94 | 0.119 | 0.067 |
| `top_option_2_threat_score` | 2.66 | 0.015 | 0.013 |
| `top_option_3_threat_score` | 1.85 | 0.011 | 0.011 |
| `angle_to_attacking_goal` | 1.71 | 0.255 | 0.200 |
| `marking_tightness` | 1.28 | 6.81 | 5.98 |

Well-behaved (skew within ~±0.35 of zero): all `top_option_{{1,2,3}}_target_x/y`, `ball_x`, `ball_y`, `defender_x`, `defender_y`, `distance_to_attacking_box`, `distance_to_defending_box`, `distance_to_attacking_goal`, `distance_to_defending_goal`.

The threat-score and lane-screening-score columns are all bounded in [0, ~1] and heavily right-skewed toward 0 -- most defender/option pairs carry negligible threat or screening value, with a long tail of high-value pairs. `n_extreme` is ~15,900-15,932 (~1.0%) for essentially every continuous column here, a mechanical consequence of the p99 definition at this row count, not a data-quality signal.

## 4. What was excluded, and why

| Column(s) | Reason |
|---|---|
| `visibility_quality_band`, `visibility_limited`, `ball_inside_visible_area`, `action_inside_visible_area`, `local_5m_region_fully_visible`, `local_10m_region_fully_visible`, `visible_area_polygon_area`, `visible_area_fraction_of_pitch` | Camera/360-tracking-coverage metadata, not a football signal. These show real statistical lift with shots, but that's a confound: crowded, high-danger zones (own-box scrambles, counters) are simultaneously harder for the 360 tracking to fully capture *and* where shots cluster. The lift is about camera coverage, not defending. |
| `action_changed_possession`, `action_ended_possession`, `action_won_possession` (active only) | Structural zero: exactly 0.00% shot rate by the target-window definition itself, not a genuine finding. |
| `freeze_frame_count` | Data-collection artifact, not a defensive feature. |
| `carrier_x`/`carrier_y` (passive) | Verified 100%-identical to `ball_x`/`ball_y` (the on-ball event's location *is* the ball location in this table) -- dropped, with `ball_x`/`ball_y` kept as canonical. |

**Open item, not buried in a footnote: `action_x`/`action_y` (active) are still a known unresolved duplicate.** They are verified 100%-identical to `ball_x`/`ball_y` in the current dataset -- the report generator's `check_duplicate_columns` assertion confirmed this again on this pass and would fail loudly if it ever stopped being true. They *should* be dropped, the same way `carrier_x`/`carrier_y` already were, but haven't been: they're required/canonical column names across 11 files in the modelling and analysis pipeline (`dax.models.schemas`/`specs`/`leakage`, `baseline_regression.py`, `baseline_logistic.py`, `dax.analysis.*`, `dax.coach_analysis.zones`, `analysis.player_features.*`), and dropping them needs a coordinated rename across all of those -- a separate, dedicated task, tracked by `tests/test_player_defense_geometry.py::test_no_duplicate_columns_on_real_player_defensive_actions_dataset`, which enforces that `action_x`/`ball_x` and `action_y`/`ball_y` are the *only* allowed duplicate pair.

## 5. Final candidate feature set

51 active features, 44 passive features, after every exclusion in Section 4.

### Active (51)

| Type | n | Columns |
|---|---|---|
| Categorical | 9 | `phase_label`, `position`, `position_group`, `event_type`, `action_family`, `play_pattern`, `action_zone`, `phase_label_prev_event`, `period` |
| Boolean | 13 | `is_in_defending_box`, `is_in_attacking_box`, `is_central_lane`, `is_wide_lane`, `is_deep_zone`, `is_high_zone`, `counterpress`, `phase_changed_since_prev_event`, `action_was_under_opponent_possession`, `action_retained_defensive_team_control`, `has_previous_event`, `has_visible_attacker`, `has_visible_defender` |
| Continuous | 18 | `match_time_seconds`, `possession_elapsed_seconds`, `distance_to_attacking_goal`, `distance_to_defending_goal`, `angle_to_attacking_goal`, `distance_to_attacking_box`, `distance_to_defending_box`, `attacking_goal_centrality`, `distance_to_center_line`, `nearest_attacker_distance`, `nearest_defender_distance`, `attacker_centroid_x`, `attacker_centroid_y`, `defender_centroid_x`, `defender_centroid_y`, `attacker_spread`, `defender_spread`, `attacker_defender_ratio` |
| Discrete | 11 | `events_elapsed_in_possession`, `phase_transitions_observed_so_far`, `visible_attacker_count`, `visible_defender_count`, `attackers_within_5m`, `defenders_within_5m`, `attackers_within_10m`, `defenders_within_10m`, `defenders_between_ball_and_attacking_goal`, `local_numerical_balance_5m`, `local_numerical_balance_10m` |

### Passive (44)

| Type | n | Columns |
|---|---|---|
| Categorical | 5 | `on_ball_event_type`, `phase_label`, `defender_zone`, `defender_functional_role`, `period` |
| Boolean | 11 | `is_in_defending_box`, `is_in_attacking_box`, `is_deep_zone`, `is_high_zone`, `is_wide_lane`, `is_central_lane`, `has_option_2`, `has_option_3`, `has_screened_outcome`, `screens_top_option`, `is_goal_side_of_nearest_attacker` |
| Continuous | 26 | `defender_x`, `defender_y`, `ball_x`, `ball_y`, `distance_to_attacking_goal`, `distance_to_defending_goal`, `angle_to_attacking_goal`, `distance_to_attacking_box`, `distance_to_defending_box`, `attacking_goal_centrality`, `distance_to_center_line`, `marking_tightness`, `zone_defensive_value`, `engagement_distance_to_carrier`, `top_option_1_target_x`, `top_option_1_target_y`, `top_option_1_threat_score`, `lane_screening_score_option_1`, `top_option_2_target_x`, `top_option_2_target_y`, `top_option_2_threat_score`, `lane_screening_score_option_2`, `top_option_3_target_x`, `top_option_3_target_y`, `top_option_3_threat_score`, `lane_screening_score_option_3` |
| Discrete | 2 | `overload_score`, `defender_slot_index` |

Cross-correlation testing has **not** been done in this pass for either dataset, so neither list has been pruned for redundancy -- e.g. `is_central_lane`/`is_wide_lane` are near-mirror pairs (active: +8.07pp vs -7.24pp; passive: +2.54pp vs -2.76pp) and `is_deep_zone`/`is_high_zone` carry near-identical lift on the active side (+7.22pp both). Both are kept as-is for now; pruning is the next EDA pass, not this one.

## 6. Open items / next steps

1. **Cross-correlation testing** across both final feature lists -- not yet done. Candidate redundant pairs already visible from lift alone: `is_central_lane`/`is_wide_lane`, `is_deep_zone`/`is_high_zone` (active).
2. **Resolve the `action_x`/`action_y` duplicate drop** (Section 4) -- requires a coordinated rename across 11 downstream modules; currently guarded only by a test asserting the duplicate is the *only* allowed exception.
3. **Small-n boolean lifts to treat with caution before modelling**: `has_visible_attacker` (active, False n=31), `has_visible_defender` (active, False n=76), `has_option_2` (passive, False n=279).
4. **`n_extreme` at ~1% is mechanical, not a red flag** -- every continuous column's extreme count is a direct consequence of the p99 clip definition; no column showed an anomalously large extreme population worth a separate follow-up.
5. **No causal claims anywhere in the modelling writeup that follows this document** -- every finding above is correlational only, per Section 2.

---

**Changelog** -- 2026-09-15: First EDA pass on the current feature builds. Reflects the `nearest_defender_distance`/`nearest_attacker_distance` actor-self-reference fix in `src/dax/features/player_defense.py` (verified 0.0% residual near-zero rows, up from 73.6%/20.0%), the `carrier_x`/`carrier_y` drop in `passive_defense.py`, the `action_inside_visible_area` drop in `player_defense.py`, and the 3+3 missingness flags added by `scripts/add_missingness_flags.py` (`has_visible_attacker`, `has_visible_defender`, `has_previous_event` on the active side; `has_option_2`, `has_option_3`, `has_screened_outcome` on the passive side). `action_x`/`action_y` remain an open, unresolved duplicate as documented in Section 4.
"""


def main() -> None:
    body_html = markdown.markdown(
        ANALYSIS_MARKDOWN,
        extensions=["tables", "fenced_code", "sane_lists"],
    )

    html = render.render_article(
        eyebrow="EDA ANALYSIS",
        title="EDA Analysis: Defensive Positioning Features",
        dek=(
            "A written synthesis of the 6 generated EDA reports: what the data shows, what's usable as a "
            "model feature, what isn't, and why."
        ),
        stats=[
            ("56,068 / 1,593,181", "rows (active / passive)"),
            ("7.79% / 5.97%", "base rate (active / passive)"),
            ("51 / 44", "candidate features (active / passive)"),
        ],
        body_html=body_html,
    )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(html, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
