"""Rung 0 of the active-continuous leg (prompt 54): hurdle regression baseline
for E[xg | shot], active leg.

Two rough chat analyses (not yet committed elsewhere in this repo, cited here)
settled the two open questions this script depends on:

  1. Distribution shape: target_future_xg_10s's shot-conditional distribution
     (rows where target_future_shot_10s==1) is heavily right-skewed (skew
     ~3.2-3.3, excess kurtosis ~13-14) and NOT bounded at 1 -- 7 of 56,068
     active rows exceed 1.0, because the target sums xG across every shot in
     the 10s window, not one shot's probability. Log-normal is the
     best-fitting family among log-normal/gamma/weibull/beta (beta is
     disqualified outright by the >1 rows). This rules in a two-part
     ("hurdle") architecture: reuse the already-promoted binary classifier
     for P(shot), fit a new regression only on the positive rows for
     E[xg | shot], on a log scale -- rather than a single Tweedie or beta
     regression across all rows.
  2. Window length: a sensitivity check (25-match sample, real
     add_future_shot_target/add_future_xg_target code from
     dax.targets.short_horizon) found the existing 10s window captures only
     ~41% of possessions that eventually produce a shot, and that
     possession-bound framing is worse (some possessions run past where the
     action's own features remain a fair predictor). Varun's explicit,
     accepted decision: keep the 10s window. This script does not revisit
     that decision -- it is a stated, documented limitation, not solved here.

Classifier half: v1e_gradient_boosting_calibrated, promoted to standing
reference model for the active-binary leg in Prompt 46 (confirmed against
reports/modeling/active_binary/ACTIVE_BINARY_MODEL_LADDER.md's own status
banner before writing this script, not assumed). Reused EXACTLY as already
fitted -- this script never retrains, refits, or re-tunes it. No saved
held-out prediction array exists for it on disk (only chart PNGs from
Prompt 45/46), so its held-out score is regenerated by loading the saved
joblib model and scoring through a freshly-fit (cheap, deterministic)
RFDesignMatrixBuilder -- the identical reuse pattern already verified to
reproduce an original held-out score exactly in Prompt 52 (p1c's held-out
PR-AUC reproduced to 0.20126 vs the recorded 0.2013).

Regression half (new): fit only on the target_future_shot_10s==1 rows
(4,368 of 56,068 -- reconfirmed directly against the real parquet, not
assumed from the rough chat estimate). Every one of these 4,368 rows has
target_future_xg_10s > 0 by construction (reconfirmed: 0 rows <= 0), so a
natural log transform is always defined, no log1p needed for c1.

  c0_dummy         -- predicts the training-fold mean of log1p(xg) for every
                       row (back-transformed via expm1 for original-scale
                       reporting). The naive floor.
  c1_lognormal_glm  -- plain LinearRegression on log(xg) (natural log), same
                       32 locked ACTIVE features and same DesignMatrixBuilder
                       preprocessing as the binary leg (imported directly
                       from train_active_binary_baseline.py, not
                       reimplemented).

Usage:
    python scripts/models/train_active_continuous_baseline.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from scipy import stats
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "scripts" / "models"))
sys.path.insert(0, str(REPO_ROOT / "src"))

import train_active_binary_baseline as ab  # noqa: E402
import train_v1d_random_forest as v1d_mod  # noqa: E402
from dax.models.diagnostics import _ACCENT, _MUTED, _new_axes, _save_fixed, ensure_dir  # noqa: E402
from dax.models.evaluation import regression_metrics  # noqa: E402
from dax.models.splits import canonical_grouped_folds, canonical_test_mask, load_canonical_split  # noqa: E402
from dax.models.two_part_xg import compute_conditional_metrics, compute_hurdle_metrics  # noqa: E402

TARGET_XG_COL = "target_future_xg_10s"
CLASSIFIER_VARIANT = "v1e_gradient_boosting_calibrated"
CLASSIFIER_JOBLIB = ab.MODELS_DIR / f"{CLASSIFIER_VARIANT}.joblib"

REG_DIR = REPO_ROOT / "outputs" / "models" / "regression"
REG_CHARTS_DIR = REG_DIR / "charts"
COMPARISONS_DIR = REPO_ROOT / "outputs" / "models" / "comparisons"
VALIDATION_DIR = REPO_ROOT / "outputs" / "models" / "validation"

VARIANTS = ["c0_dummy", "c1_lognormal_glm"]


# ---------------------------------------------------------------------------
# Fold-safe fit/predict for the two regression variants.
# ---------------------------------------------------------------------------

def fit_predict_regression(train_df: pd.DataFrame, test_df: pd.DataFrame, variant: str):
    """Returns (log_pred, log_sigma2, model_or_None, extra_or_None).

    log_sigma2 is the training-fold residual variance on the log scale --
    needed for the log-normal mean-correction back-transform
    exp(pred + sigma^2/2), computed once per fit from that fit's own
    training residuals (never from test rows).
    """
    y_train_log = np.log(train_df[TARGET_XG_COL].to_numpy())

    if variant == "c0_dummy":
        y_train_log1p = np.log1p(train_df[TARGET_XG_COL].to_numpy())
        model = DummyRegressor(strategy="mean")
        model.fit(np.zeros((len(train_df), 1)), y_train_log1p)
        pred_log1p = model.predict(np.zeros((len(test_df), 1)))
        # Reported log-scale figure for c0 is on the log1p scale (per this
        # variant's own definition) -- back-transform via expm1 for the
        # original-scale xg prediction used everywhere else.
        resid = y_train_log1p - model.predict(np.zeros((len(train_df), 1)))
        sigma2 = float(np.var(resid, ddof=1)) if len(resid) > 1 else 0.0
        return pred_log1p, sigma2, model, None

    builder = ab.DesignMatrixBuilder(add_interactions=False, add_quadratic=False).fit(train_df)
    x_train, feature_names = builder.transform(train_df)
    x_test, _ = builder.transform(test_df)

    model = LinearRegression()
    model.fit(x_train, y_train_log)
    pred_log = model.predict(x_test)
    resid = y_train_log - model.predict(x_train)
    sigma2 = float(np.var(resid, ddof=1)) if len(resid) > 1 else 0.0
    return pred_log, sigma2, model, (builder, feature_names)


def backtransform(log_pred: np.ndarray, sigma2: float, method: str) -> np.ndarray:
    if method == "naive":
        return np.exp(log_pred)
    if method == "lognormal_corrected":
        return np.exp(log_pred + sigma2 / 2.0)
    raise ValueError(method)


# ---------------------------------------------------------------------------
# CV
# ---------------------------------------------------------------------------

def run_cv_regression(pos_trainval_df: pd.DataFrame, variant: str) -> dict:
    folds = canonical_grouped_folds(pos_trainval_df, group_col=ab.GROUP_COL)
    df = pos_trainval_df.loc[folds["row_index"]].copy()
    df["fold"] = folds["fold"].to_numpy()

    fold_rows = []
    oof_log_pred = np.full(len(df), np.nan)
    oof_sigma2 = np.full(len(df), np.nan)

    for fold_id in sorted(df["fold"].unique()):
        train_mask = (df["fold"] != fold_id).to_numpy()
        test_mask = (df["fold"] == fold_id).to_numpy()
        train_df, test_df = df.loc[train_mask], df.loc[test_mask]

        log_pred, sigma2, _, _ = fit_predict_regression(train_df, test_df, variant)
        oof_log_pred[test_mask] = log_pred
        oof_sigma2[test_mask] = sigma2

        y_true_log = np.log1p(test_df[TARGET_XG_COL].to_numpy()) if variant == "c0_dummy" else np.log(test_df[TARGET_XG_COL].to_numpy())
        log_resid = log_pred - y_true_log
        xg_naive = backtransform(log_pred, sigma2, "naive") if variant != "c0_dummy" else np.expm1(log_pred)
        xg_corrected = backtransform(log_pred, sigma2, "lognormal_corrected") if variant != "c0_dummy" else xg_naive
        y_true_xg = test_df[TARGET_XG_COL].to_numpy()

        # common_log_* puts both variants on the SAME natural-log(xg) scale for a fair
        # head-to-head comparison -- c0's own "native" log_rmse/log_mae above are on the
        # log1p scale per this variant's own definition, and log1p(x) vs log(x) are not
        # comparable numbers (log1p(0.05)=0.049, log(0.05)=-3.0), so native log_rmse
        # cannot be used to judge which variant is better. common_log_* re-expresses
        # BOTH variants' already-computed xg-scale predictions in natural log for a
        # like-for-like comparison, and is what the significance test (item 3) actually uses.
        common_log_resid = np.log(xg_naive) - np.log(y_true_xg)
        m = {
            "fold": int(fold_id),
            "n_train": int(train_mask.sum()),
            "n_test": int(test_mask.sum()),
            "log_rmse": float(np.sqrt(np.mean(log_resid ** 2))),
            "log_mae": float(np.mean(np.abs(log_resid))),
            "common_log_rmse": float(np.sqrt(np.mean(common_log_resid ** 2))),
            "common_log_mae": float(np.mean(np.abs(common_log_resid))),
        }
        m.update({f"naive_{k}": v for k, v in regression_metrics(y_true_xg, xg_naive).items()})
        m.update({f"corrected_{k}": v for k, v in regression_metrics(y_true_xg, xg_corrected).items()})
        fold_rows.append(m)

    fold_df = pd.DataFrame(fold_rows)

    y_true_log_all = np.log1p(df[TARGET_XG_COL].to_numpy()) if variant == "c0_dummy" else np.log(df[TARGET_XG_COL].to_numpy())
    oof_log_resid = oof_log_pred - y_true_log_all
    oof_xg_naive = np.expm1(oof_log_pred) if variant == "c0_dummy" else backtransform(oof_log_pred, oof_sigma2, "naive")
    oof_xg_corrected = oof_xg_naive if variant == "c0_dummy" else backtransform(oof_log_pred, oof_sigma2, "lognormal_corrected")
    y_true_xg_all = df[TARGET_XG_COL].to_numpy()

    oof_common_log_resid = np.log(oof_xg_naive) - np.log(y_true_xg_all)
    oof_metrics = {
        "log_rmse": float(np.sqrt(np.mean(oof_log_resid ** 2))),
        "log_mae": float(np.mean(np.abs(oof_log_resid))),
        "common_log_rmse": float(np.sqrt(np.mean(oof_common_log_resid ** 2))),
        "common_log_mae": float(np.mean(np.abs(oof_common_log_resid))),
    }
    oof_metrics.update({f"naive_{k}": v for k, v in regression_metrics(y_true_xg_all, oof_xg_naive).items()})
    oof_metrics.update({f"corrected_{k}": v for k, v in regression_metrics(y_true_xg_all, oof_xg_corrected).items()})

    return {
        "variant": variant,
        "fold_metrics": fold_df,
        "oof_metrics": oof_metrics,
        "oof_log_pred": oof_log_pred,
        "oof_xg_naive": oof_xg_naive,
        "oof_xg_corrected": oof_xg_corrected,
        "y_true_xg": y_true_xg_all,
        "df": df,
    }


def calibration_bins(y_true: np.ndarray, y_pred: np.ndarray, n_bins: int = 5) -> list[dict]:
    order = np.argsort(y_pred)
    y_true_sorted = y_true[order]
    y_pred_sorted = y_pred[order]
    edges = np.array_split(np.arange(len(y_pred_sorted)), n_bins)
    rows = []
    for i, idx in enumerate(edges):
        if len(idx) == 0:
            continue
        rows.append({
            "bin": i,
            "n": int(len(idx)),
            "mean_predicted": float(y_pred_sorted[idx].mean()),
            "mean_actual": float(y_true_sorted[idx].mean()),
            "gap": float(y_pred_sorted[idx].mean() - y_true_sorted[idx].mean()),
        })
    return rows


def append_to_csv(path: Path, new_rows: list[dict]) -> None:
    """Appends rows, unioning columns (not restricting to the existing file's
    columns) so a schema addition on a later run is never silently dropped."""
    new_df = pd.DataFrame(new_rows)
    if path.exists():
        existing = pd.read_csv(path)
        all_cols = list(existing.columns) + [c for c in new_df.columns if c not in existing.columns]
        existing = existing.reindex(columns=all_cols)
        new_df = new_df.reindex(columns=all_cols)
        combined = pd.concat([existing, new_df], ignore_index=True)
    else:
        combined = new_df
    combined.to_csv(path, index=False)


# ---------------------------------------------------------------------------
# Charts
# ---------------------------------------------------------------------------

def save_regression_variant_charts(chart_dir: Path, y_true_log, y_pred_log, y_true_xg, y_pred_xg, calib_rows, coef_table):
    ensure_dir(chart_dir)

    fig, ax = _new_axes()
    ax.scatter(y_pred_log, y_true_log, alpha=0.35, s=14, color=_ACCENT, edgecolor="none")
    lo = float(min(np.min(y_pred_log), np.min(y_true_log)))
    hi = float(max(np.max(y_pred_log), np.max(y_true_log)))
    ax.plot([lo, hi], [lo, hi], color=_MUTED, linewidth=1.2, linestyle="--", label="y = x")
    ax.legend(loc="upper left")
    ax.set_xlabel("Predicted log(xg)")
    ax.set_ylabel("Observed log(xg)")
    ax.set_title("Predicted vs observed (log scale)")
    _save_fixed(fig, chart_dir / "predicted_vs_observed_log.png")

    resid = y_pred_log - y_true_log
    fig, ax = _new_axes()
    ax.hist(resid, bins=20, color=_ACCENT, edgecolor="#1e3a8a", linewidth=0.6, alpha=0.85)
    ax.axvline(0, color=_MUTED, linewidth=1.2, linestyle="--")
    ax.set_xlabel("Residual (log scale)")
    ax.set_ylabel("Count")
    ax.set_title("Residual distribution (log scale)")
    _save_fixed(fig, chart_dir / "residual_distribution.png")

    fig, ax = _new_axes()
    bins_x = [r["mean_predicted"] for r in calib_rows]
    bins_pred = [r["mean_predicted"] for r in calib_rows]
    bins_actual = [r["mean_actual"] for r in calib_rows]
    ax.plot(bins_x, bins_pred, marker="o", color=_ACCENT, linewidth=2, label="mean predicted")
    ax.plot(bins_x, bins_actual, marker="s", color=_MUTED, linewidth=2, label="mean actual")
    ax.legend(loc="upper left")
    ax.set_xlabel("Bin (ordered by predicted xg)")
    ax.set_ylabel("xg")
    ax.set_title("Calibration: mean predicted vs mean actual xg, by bin")
    _save_fixed(fig, chart_dir / "calibration_bins.png")

    fig, ax = _new_axes()
    if coef_table is not None and len(coef_table) > 0:
        top = coef_table.reindex(coef_table["abs_coef"].sort_values(ascending=False).index)[:15]
        ax.barh(top["feature"][::-1], top["coef"][::-1], color=_ACCENT)
        ax.set_xlabel("Coefficient (log-xg scale)")
        ax.set_title("Top 15 |coefficient|")
    else:
        ax.text(0.5, 0.5, "No features (dummy variant)", ha="center", va="center", transform=ax.transAxes, color=_MUTED)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_title("Feature coefficients (n/a)")
    _save_fixed(fig, chart_dir / "feature_coefficients.png")


# ---------------------------------------------------------------------------
# Classifier scoring (reuse only, never refit)
# ---------------------------------------------------------------------------

def score_classifier(trainval_full_df: pd.DataFrame, target_df: pd.DataFrame) -> np.ndarray:
    if not CLASSIFIER_JOBLIB.exists():
        raise FileNotFoundError(
            f"Expected promoted classifier artifact not found at {CLASSIFIER_JOBLIB}. "
            "This script's whole premise depends on reusing a real, already-validated artifact -- "
            "stopping rather than silently retraining it."
        )
    builder = v1d_mod.RFDesignMatrixBuilder().fit(trainval_full_df)
    x, _ = builder.transform(target_df)
    model = joblib.load(CLASSIFIER_JOBLIB)
    return model.predict_proba(x)[:, 1]


def main() -> None:
    REG_DIR.mkdir(parents=True, exist_ok=True)
    REG_CHARTS_DIR.mkdir(parents=True, exist_ok=True)
    COMPARISONS_DIR.mkdir(parents=True, exist_ok=True)
    VALIDATION_DIR.mkdir(parents=True, exist_ok=True)

    print("[1/6] confirming inputs...")
    assert CLASSIFIER_JOBLIB.exists(), f"Promoted classifier not found: {CLASSIFIER_JOBLIB}"
    print(f"  classifier artifact confirmed: {CLASSIFIER_JOBLIB}")
    assert len(ab.ALL_FEATURE_COLS) == 32
    print(f"  32 locked ACTIVE features confirmed (6 categorical + 9 boolean + 17 numeric)")

    df_all = ab.load_data()
    load_canonical_split()
    test_mask_full = canonical_test_mask(df_all, group_col=ab.GROUP_COL)
    trainval_full = df_all.loc[~test_mask_full].reset_index(drop=True)
    test_full = df_all.loc[test_mask_full].reset_index(drop=True)

    pos_all = df_all[df_all[ab.TARGET_COL] == 1].reset_index(drop=True)
    print(f"  positive rows (target_future_shot_10s==1): {len(pos_all)} of {len(df_all)}")
    print(f"  positive rows with xg>1: {int((pos_all[TARGET_XG_COL] > 1).sum())}; xg<=0: {int((pos_all[TARGET_XG_COL] <= 0).sum())}")

    pos_test_mask = canonical_test_mask(pos_all, group_col=ab.GROUP_COL)
    pos_trainval = pos_all.loc[~pos_test_mask].reset_index(drop=True)
    pos_test = pos_all.loc[pos_test_mask].reset_index(drop=True)
    print(f"  positive trainval rows: {len(pos_trainval)} ({pos_trainval[ab.GROUP_COL].nunique()} matches); "
          f"positive held-out test rows: {len(pos_test)} ({pos_test[ab.GROUP_COL].nunique()} matches)")

    fold_probe = canonical_grouped_folds(pos_trainval, group_col=ab.GROUP_COL)
    fold_counts = pd.Series(fold_probe["fold"].to_numpy()).value_counts().sort_index()
    print(f"  positive rows per canonical fold: {fold_counts.to_dict()}")
    thin_folds = fold_counts[fold_counts < 100]
    if len(thin_folds) > 0:
        print(f"  [FLAG] thin fold(s) with <100 positive rows: {thin_folds.to_dict()} -- CV metrics on these folds should be read cautiously")
    else:
        print("  no fold has fewer than 100 positive rows -- CV metrics are on reasonably stable per-fold sample sizes")

    print("\n[2/6] cross-validation, c0_dummy and c1_lognormal_glm...")
    comparison_rows = []
    cv_results = {}
    for variant in VARIANTS:
        print(f"  [cv] {variant}")
        result = run_cv_regression(pos_trainval, variant)
        cv_results[variant] = result
        row = {"variant": variant, "n_features": 0 if variant == "c0_dummy" else 32}
        row.update(result["oof_metrics"])
        row["rows"] = len(pos_trainval)
        row["matches"] = pos_trainval[ab.GROUP_COL].nunique()
        comparison_rows.append(row)

    print("\n[3/6] significance test, c1 vs c0 (common-scale natural-log(xg) RMSE per fold)...")
    # NOT c0's/c1's own "native" log_rmse -- those are on different scales (c0 is fit and
    # evaluated on log1p(xg), c1 on log(xg); log1p(0.05)=0.049 vs log(0.05)=-3.0 are not
    # comparable numbers, so a native-scale comparison would make c1 look far worse purely
    # from the transform, not the model). common_log_rmse re-expresses both variants'
    # xg-scale (naive back-transform) predictions in natural log for a fair comparison.
    fold_common_log_rmse = {v: cv_results[v]["fold_metrics"]["common_log_rmse"].tolist() for v in VARIANTS}
    fold_native_log_rmse = {v: cv_results[v]["fold_metrics"]["log_rmse"].tolist() for v in VARIANTS}
    a = np.array(fold_common_log_rmse["c1_lognormal_glm"])
    b = np.array(fold_common_log_rmse["c0_dummy"])
    diff = a - b  # negative = c1 better (lower RMSE)
    t_stat, p_val = stats.ttest_rel(a, b)
    if len(set(diff.round(12))) > 1:
        w_stat, w_p = stats.wilcoxon(a, b)
    else:
        w_stat, w_p = float("nan"), float("nan")
    sig = {
        "metric": "common_log_rmse (per fold, natural-log(xg) scale for both variants, lower is better)",
        "scale_mismatch_note": (
            "c0_dummy is fit and natively evaluated on log1p(xg) (per its own Rung-0 definition), "
            "c1_lognormal_glm on log(xg) -- these are NOT directly comparable numbers (e.g. "
            "log1p(0.05)=0.049 vs log(0.05)=-3.0). Both variants' native-scale fold RMSEs are "
            "included below for transparency (fold_native_log_rmse) but were NOT used for this "
            "significance test -- common_log_rmse (natural log of both variants' xg-scale "
            "predictions) is used instead, for a fair head-to-head comparison."
        ),
        "fold_common_log_rmse": fold_common_log_rmse,
        "fold_native_log_rmse": fold_native_log_rmse,
        "mean_diff_c1_minus_c0": float(diff.mean()),
        "std_diff": float(diff.std(ddof=1)),
        "paired_t_stat": float(t_stat),
        "paired_t_pvalue": float(p_val),
        "wilcoxon_stat": float(w_stat) if w_stat == w_stat else None,
        "wilcoxon_pvalue": float(w_p) if w_p == w_p else None,
        "n_folds": int(len(a)),
        "caution_note": (
            "5 folds only, with a few hundred positive rows per fold (this leg's much smaller sample "
            "than the binary legs) -- read this test as directionally informative, not as strong "
            "statistical proof, the same honest caveat given to every small-n significance test "
            "elsewhere in this project."
        ),
    }
    (VALIDATION_DIR / "significance_c0_vs_c1.json").write_text(json.dumps(sig, indent=2), encoding="utf-8")
    print(f"  mean_diff (c1-c0) log_rmse: {sig['mean_diff_c1_minus_c0']:+.4f}, paired_t_p={sig['paired_t_pvalue']:.4f}, wilcoxon_p={sig['wilcoxon_pvalue']}")

    print("\n[4/6] held-out test readout (fit once on all positive trainval rows)...")
    held_out_rows = []
    final_models = {}
    for variant in VARIANTS:
        log_pred, sigma2, model, extra = fit_predict_regression(pos_trainval, pos_test, variant)
        final_models[variant] = (model, extra, sigma2)

        y_true_log = np.log1p(pos_test[TARGET_XG_COL].to_numpy()) if variant == "c0_dummy" else np.log(pos_test[TARGET_XG_COL].to_numpy())
        y_true_xg = pos_test[TARGET_XG_COL].to_numpy()
        log_resid = log_pred - y_true_log

        xg_naive = np.expm1(log_pred) if variant == "c0_dummy" else backtransform(log_pred, sigma2, "naive")
        xg_corrected = xg_naive if variant == "c0_dummy" else backtransform(log_pred, sigma2, "lognormal_corrected")
        common_log_resid = np.log(xg_naive) - np.log(y_true_xg)

        row = {"variant": variant, "readout": "FINAL_HELD_OUT_TEST_NOT_FOR_SELECTION",
               "rows": len(pos_test), "matches": pos_test[ab.GROUP_COL].nunique(),
               "log_rmse": float(np.sqrt(np.mean(log_resid ** 2))), "log_mae": float(np.mean(np.abs(log_resid))),
               "common_log_rmse": float(np.sqrt(np.mean(common_log_resid ** 2))),
               "common_log_mae": float(np.mean(np.abs(common_log_resid)))}
        row.update({f"naive_{k}": v for k, v in regression_metrics(y_true_xg, xg_naive).items()})
        row.update({f"corrected_{k}": v for k, v in regression_metrics(y_true_xg, xg_corrected).items()})
        held_out_rows.append(row)

        calib_variant_pred = xg_corrected if variant != "c0_dummy" else xg_naive
        calib_rows = calibration_bins(y_true_xg, calib_variant_pred)

        coef_table = None
        if variant == "c1_lognormal_glm":
            builder, feature_names = extra
            coefs = model.coef_
            coef_table = pd.DataFrame({
                "feature": feature_names,
                "coef": coefs,
                "abs_coef": np.abs(coefs),
            }).sort_values("abs_coef", ascending=False).reset_index(drop=True)
            coeff_json = {
                "variant": variant,
                "intercept": float(model.intercept_),
                "n_features": len(feature_names),
                "coefficients": coef_table.to_dict(orient="records"),
                "fitted_on": "all positive-row train+val rows (canonical split); held-out test used once for readout only",
            }
            (REG_DIR / f"{variant}.json").write_text(json.dumps(coeff_json, indent=2), encoding="utf-8")

        save_regression_variant_charts(
            REG_CHARTS_DIR / variant, y_true_log, log_pred, y_true_xg, calib_variant_pred, calib_rows, coef_table
        )
        joblib.dump(model, REG_DIR / f"{variant}.joblib")
        print(f"  [held-out] {variant}: log_rmse={row['log_rmse']:.4f} naive_mae={row['naive_mae']:.4f} corrected_mae={row['corrected_mae']:.4f} naive_r2={row['naive_r2']:.4f} corrected_r2={row['corrected_r2']:.4f}")

    print("\n[5/6] writing comparison CSVs...")
    append_to_csv(COMPARISONS_DIR / "active_continuous_baseline_comparison.csv", comparison_rows)
    append_to_csv(COMPARISONS_DIR / "active_continuous_baseline_held_out_test_readout.csv", held_out_rows)

    print("\n[6/6] full hurdle pipeline readout (diagnostic, not the Rung-0 gate)...")
    c1_model, c1_extra, c1_sigma2 = final_models["c1_lognormal_glm"]
    c1_builder, c1_feature_names = c1_extra
    x_full_test, _ = c1_builder.transform(test_full)
    log_pred_full = c1_model.predict(x_full_test)
    e_xg_given_shot = backtransform(log_pred_full, c1_sigma2, "lognormal_corrected")

    p_shot_full_test = score_classifier(trainval_full, test_full)

    combined_pred = p_shot_full_test * e_xg_given_shot
    hurdle_oof = pd.DataFrame({
        "observed_future_xg": test_full[TARGET_XG_COL].to_numpy(),
        "combined_future_xg_prediction": combined_pred,
        "match_id": test_full[ab.GROUP_COL].to_numpy(),
    })
    hurdle_metrics = compute_hurdle_metrics(hurdle_oof, prediction_col="combined_future_xg_prediction")

    trivial_mean = float(trainval_full[TARGET_XG_COL].mean())
    trivial_pred = np.full(len(test_full), trivial_mean)
    trivial_oof = pd.DataFrame({
        "observed_future_xg": test_full[TARGET_XG_COL].to_numpy(),
        "trivial_prediction": trivial_pred,
        "match_id": test_full[ab.GROUP_COL].to_numpy(),
    })
    trivial_metrics = compute_hurdle_metrics(trivial_oof, prediction_col="trivial_prediction")

    hurdle_readout = {
        "held_out_test_rows": len(test_full),
        "held_out_test_matches": int(test_full[ab.GROUP_COL].nunique()),
        "classifier_variant": CLASSIFIER_VARIANT,
        "regression_variant": "c1_lognormal_glm (lognormal_corrected back-transform)",
        "hurdle_pipeline_metrics": hurdle_metrics,
        "trivial_unconditional_mean_baseline": trivial_mean,
        "trivial_baseline_metrics": trivial_metrics,
        "note": (
            "Diagnostic readout only -- not the Rung-0 gate. Rung-0 promotion is decided by the "
            "regression-only c1-vs-c0 comparison (significance_c0_vs_c1.json), not by this end-to-end "
            "hurdle number."
        ),
    }
    (VALIDATION_DIR / "hurdle_pipeline_readout.json").write_text(json.dumps(hurdle_readout, indent=2), encoding="utf-8")
    print(f"  hurdle pipeline: rmse={hurdle_metrics['rmse']:.4f} mae={hurdle_metrics['mae']:.4f} r2={hurdle_metrics['r2']:.4f}")
    print(f"  trivial baseline: rmse={trivial_metrics['rmse']:.4f} mae={trivial_metrics['mae']:.4f} r2={trivial_metrics['r2']:.4f}")

    print("\n=== CV comparison (5-fold, OOF metrics; common_log_rmse is the fair cross-variant comparison) ===")
    print(pd.DataFrame(comparison_rows)[["variant", "common_log_rmse", "common_log_mae", "naive_mae", "corrected_mae", "naive_r2", "corrected_r2"]].to_string(index=False))
    print("\n=== Held-out test readout ===")
    print(pd.DataFrame(held_out_rows)[["variant", "common_log_rmse", "naive_mae", "corrected_mae", "naive_r2", "corrected_r2"]].to_string(index=False))
    print("\nDone.")


if __name__ == "__main__":
    main()
