"""Rung 0 of the passive-continuous leg (prompt 59): hurdle regression baseline
for E[xg | shot], passive leg. Fourth and final leg of the project.

Mirrors train_active_continuous_baseline.py's own Rung 0 (prompt 54) closely --
same hurdle architecture, same reasoning -- but two things about the passive
dataset are genuinely different, both reconfirmed directly against real data
before writing this script (not assumed to transfer from the active leg):

  1. Distribution shape transfers almost exactly. target_future_xg_10s on
     data/features/passive_defense.parquet's positive rows (n=95,048) has raw
     skew 3.28 / excess kurtosis 14.0, log-scale skew 0.19 / excess kurtosis
     -0.13 -- essentially the same shape as the active leg's own target. 67 of
     the 95,048 positive rows exceed xg=1.0 (0 rows <= 0), same reasoning as
     the active leg (the target sums xG across every shot in the window, not
     one shot's probability). Log-normal hurdle architecture applies
     unchanged: reuse the already-promoted p1e_gradient_boosting_calibrated
     (Prompt 52) for P(shot), fit a new regression only on the positive rows
     for E[xg | shot], on a log scale.
  2. Row grain creates real duplication that must be documented, not silently
     absorbed. passive_defense.parquet is one row per visible defender-slot
     per on-ball attacking event. Among positive rows: 95,048 rows come from
     only 10,700 unique events (~8.9 defender-slot rows/event), and every row
     sharing an event_id has the identical target_future_xg_10s value (0
     events with >1 distinct value, reconfirmed) -- the same shot outcome,
     viewed from a different defender's geometry. Varun's explicit decision:
     fit on all defender-slot rows as-is (this IS the leg's premise -- does
     this defender's positioning explain the outcome -- not a duplication bug
     to engineer away), but report the effective-sample-size caveat plainly:
     ~10,700 independent shot events underlie the 95,048 training rows, and
     any CV fold's aggregate metric implicitly weights events with more
     visible defenders more heavily than events with fewer.

Window length: NOT reopened here. Prompt 54's sensitivity check ran on the
real add_future_shot_target/add_future_xg_target code (dax.targets.short_horizon),
which is leg-agnostic (operates on event/possession timing, not the
active/passive feature split) -- the same 10s-window decision applies
unchanged. Cross-referenced in the report, not re-derived.

Classifier half: p1e_gradient_boosting_calibrated, the passive-binary leg's
own promoted standing reference model (Prompt 52). Reused EXACTLY as already
fitted -- this script never retrains, refits, or re-tunes it. No saved
held-out prediction array exists for it on disk, so its held-out score is
regenerated by loading the saved joblib model and scoring through a
freshly-fit (cheap, deterministic) RFDesignMatrixBuilder -- the identical
reuse pattern the active leg's own baseline script used for its classifier.

Regression half (new): fit only on the target_future_shot_10s==1 rows
(95,048 of 1,593,181 -- reconfirmed directly against the real parquet).
Every one of these rows has target_future_xg_10s > 0 by construction, so a
natural log transform is always defined, no log1p needed for d1.

  d0_dummy         -- predicts the training-fold mean of log1p(xg) for every
                       row (back-transformed via expm1). The naive floor.
  d1_lognormal_glm  -- plain LinearRegression on log(xg) (natural log, same
                       estimator train_active_continuous_baseline.py used for
                       c1_lognormal_glm), same 38 locked PASSIVE features and
                       same DesignMatrixBuilder preprocessing as the passive
                       binary leg (imported directly, not reimplemented).

Naming: c0/c1 already means something on the active-continuous leg, p0/p1
already means something on the passive-binary leg -- this leg uses d0/d1
("d" for the passive leg's defender-slot regression) to avoid colliding with
either existing prefix, the first letter not already claimed by another leg.

Usage:
    python scripts/models/train_passive_continuous_baseline.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from scipy import stats
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "scripts" / "models"))
sys.path.insert(0, str(REPO_ROOT / "src"))

import train_p1d_random_forest as p1d_mod  # noqa: E402
import train_passive_binary_baseline as pb  # noqa: E402
from dax.models.diagnostics import _ACCENT, _MUTED, _new_axes, _save_fixed, ensure_dir  # noqa: E402
from dax.models.evaluation import regression_metrics  # noqa: E402
from dax.models.splits import canonical_grouped_folds, canonical_test_mask, load_canonical_split  # noqa: E402
from dax.models.two_part_xg import compute_hurdle_metrics  # noqa: E402

TARGET_XG_COL = "target_future_xg_10s"
EVENT_COL = "event_id"
CLASSIFIER_VARIANT = "p1e_gradient_boosting_calibrated"
CLASSIFIER_JOBLIB = pb.MODELS_DIR / f"{CLASSIFIER_VARIANT}.joblib"

REG_DIR = REPO_ROOT / "outputs" / "models" / "regression"
REG_CHARTS_DIR = REG_DIR / "charts"
COMPARISONS_DIR = REPO_ROOT / "outputs" / "models" / "comparisons"
VALIDATION_DIR = REPO_ROOT / "outputs" / "models" / "validation"

VARIANTS = ["d0_dummy", "d1_lognormal_glm"]


# ---------------------------------------------------------------------------
# Fold-safe fit/predict for the two regression variants.
# ---------------------------------------------------------------------------

def fit_predict_regression(train_df: pd.DataFrame, test_df: pd.DataFrame, variant: str):
    """Returns (log_pred, log_sigma2, model_or_None, extra_or_None). Same
    contract as train_active_continuous_baseline.py's own function."""
    y_train_log = np.log(train_df[TARGET_XG_COL].to_numpy())

    if variant == "d0_dummy":
        y_train_log1p = np.log1p(train_df[TARGET_XG_COL].to_numpy())
        model = DummyRegressor(strategy="mean")
        model.fit(np.zeros((len(train_df), 1)), y_train_log1p)
        pred_log1p = model.predict(np.zeros((len(test_df), 1)))
        resid = y_train_log1p - model.predict(np.zeros((len(train_df), 1)))
        sigma2 = float(np.var(resid, ddof=1)) if len(resid) > 1 else 0.0
        return pred_log1p, sigma2, model, None

    builder = pb.DesignMatrixBuilder(add_interactions=False, add_quadratic=False).fit(train_df)
    x_train, feature_names = builder.transform(train_df)
    x_test, _ = builder.transform(test_df)

    model = LinearRegression()
    model.fit(x_train, y_train_log)
    pred_log = model.predict(x_test)
    resid = y_train_log - model.predict(x_train)
    sigma2 = float(np.var(resid, ddof=1)) if len(resid) > 1 else 0.0
    return pred_log, sigma2, model, (builder, feature_names)


def backtransform(log_pred: np.ndarray, sigma2: float, method: str) -> np.ndarray:
    if method == "naive":
        return np.exp(log_pred)
    if method == "lognormal_corrected":
        return np.exp(log_pred + sigma2 / 2.0)
    raise ValueError(method)


# ---------------------------------------------------------------------------
# CV
# ---------------------------------------------------------------------------

def run_cv_regression(pos_trainval_df: pd.DataFrame, variant: str) -> dict:
    folds = canonical_grouped_folds(pos_trainval_df, group_col=pb.GROUP_COL)
    df = pos_trainval_df.loc[folds["row_index"]].copy()
    df["fold"] = folds["fold"].to_numpy()

    fold_rows = []
    oof_log_pred = np.full(len(df), np.nan)
    oof_sigma2 = np.full(len(df), np.nan)

    for fold_id in sorted(df["fold"].unique()):
        train_mask = (df["fold"] != fold_id).to_numpy()
        test_mask = (df["fold"] == fold_id).to_numpy()
        train_df, test_df = df.loc[train_mask], df.loc[test_mask]

        log_pred, sigma2, _, _ = fit_predict_regression(train_df, test_df, variant)
        oof_log_pred[test_mask] = log_pred
        oof_sigma2[test_mask] = sigma2

        y_true_log = np.log1p(test_df[TARGET_XG_COL].to_numpy()) if variant == "d0_dummy" else np.log(test_df[TARGET_XG_COL].to_numpy())
        log_resid = log_pred - y_true_log
        xg_naive = backtransform(log_pred, sigma2, "naive") if variant != "d0_dummy" else np.expm1(log_pred)
        xg_corrected = backtransform(log_pred, sigma2, "lognormal_corrected") if variant != "d0_dummy" else xg_naive
        y_true_xg = test_df[TARGET_XG_COL].to_numpy()

        # Same common_log_* fix Prompt 54 introduced on the active leg -- d0 is
        # fit/evaluated on log1p(xg), d1 on log(xg); these are not directly
        # comparable, so common_log_* re-expresses BOTH variants' xg-scale
        # predictions in natural log for a fair head-to-head comparison.
        common_log_resid = np.log(xg_naive) - np.log(y_true_xg)
        m = {
            "fold": int(fold_id),
            "n_train": int(train_mask.sum()), "n_test": int(test_mask.sum()),
            "n_train_events": int(train_df[EVENT_COL].nunique()), "n_test_events": int(test_df[EVENT_COL].nunique()),
            "log_rmse": float(np.sqrt(np.mean(log_resid ** 2))),
            "log_mae": float(np.mean(np.abs(log_resid))),
            "common_log_rmse": float(np.sqrt(np.mean(common_log_resid ** 2))),
            "common_log_mae": float(np.mean(np.abs(common_log_resid))),
        }
        m.update({f"naive_{k}": v for k, v in regression_metrics(y_true_xg, xg_naive).items()})
        m.update({f"corrected_{k}": v for k, v in regression_metrics(y_true_xg, xg_corrected).items()})
        fold_rows.append(m)

    fold_df = pd.DataFrame(fold_rows)

    y_true_log_all = np.log1p(df[TARGET_XG_COL].to_numpy()) if variant == "d0_dummy" else np.log(df[TARGET_XG_COL].to_numpy())
    oof_log_resid = oof_log_pred - y_true_log_all
    oof_xg_naive = np.expm1(oof_log_pred) if variant == "d0_dummy" else backtransform(oof_log_pred, oof_sigma2, "naive")
    oof_xg_corrected = oof_xg_naive if variant == "d0_dummy" else backtransform(oof_log_pred, oof_sigma2, "lognormal_corrected")
    y_true_xg_all = df[TARGET_XG_COL].to_numpy()

    oof_common_log_resid = np.log(oof_xg_naive) - np.log(y_true_xg_all)
    oof_metrics = {
        "log_rmse": float(np.sqrt(np.mean(oof_log_resid ** 2))),
        "log_mae": float(np.mean(np.abs(oof_log_resid))),
        "common_log_rmse": float(np.sqrt(np.mean(oof_common_log_resid ** 2))),
        "common_log_mae": float(np.mean(np.abs(oof_common_log_resid))),
    }
    oof_metrics.update({f"naive_{k}": v for k, v in regression_metrics(y_true_xg_all, oof_xg_naive).items()})
    oof_metrics.update({f"corrected_{k}": v for k, v in regression_metrics(y_true_xg_all, oof_xg_corrected).items()})

    return {
        "variant": variant, "fold_metrics": fold_df, "oof_metrics": oof_metrics,
        "oof_log_pred": oof_log_pred, "df": df,
    }


def calibration_bins(y_true: np.ndarray, y_pred: np.ndarray, n_bins: int = 5) -> list[dict]:
    order = np.argsort(y_pred)
    y_true_sorted = y_true[order]
    y_pred_sorted = y_pred[order]
    edges = np.array_split(np.arange(len(y_pred_sorted)), n_bins)
    rows = []
    for i, idx in enumerate(edges):
        if len(idx) == 0:
            continue
        rows.append({
            "bin": i, "n": int(len(idx)),
            "mean_predicted": float(y_pred_sorted[idx].mean()),
            "mean_actual": float(y_true_sorted[idx].mean()),
            "gap": float(y_pred_sorted[idx].mean() - y_true_sorted[idx].mean()),
        })
    return rows


def append_to_csv(path: Path, new_rows: list[dict]) -> None:
    """Union-of-columns append (Prompt 54's own fix) -- never restrict new
    rows to the pre-existing file's column set."""
    new_df = pd.DataFrame(new_rows)
    if path.exists():
        existing = pd.read_csv(path)
        all_cols = list(existing.columns) + [c for c in new_df.columns if c not in existing.columns]
        existing = existing.reindex(columns=all_cols)
        new_df = new_df.reindex(columns=all_cols)
        combined = pd.concat([existing, new_df], ignore_index=True)
    else:
        combined = new_df
    combined.to_csv(path, index=False)


# ---------------------------------------------------------------------------
# Charts
# ---------------------------------------------------------------------------

def save_regression_variant_charts(chart_dir: Path, y_true_log, y_pred_log, y_true_xg, y_pred_xg, calib_rows, coef_table):
    ensure_dir(chart_dir)

    fig, ax = _new_axes()
    ax.scatter(y_pred_log, y_true_log, alpha=0.15, s=10, color=_ACCENT, edgecolor="none")
    lo = float(min(np.min(y_pred_log), np.min(y_true_log)))
    hi = float(max(np.max(y_pred_log), np.max(y_true_log)))
    ax.plot([lo, hi], [lo, hi], color=_MUTED, linewidth=1.2, linestyle="--", label="y = x")
    ax.legend(loc="upper left")
    ax.set_xlabel("Predicted log(xg)")
    ax.set_ylabel("Observed log(xg)")
    ax.set_title("Predicted vs observed (log scale)")
    _save_fixed(fig, chart_dir / "predicted_vs_observed_log.png")

    resid = y_pred_log - y_true_log
    fig, ax = _new_axes()
    ax.hist(resid, bins=20, color=_ACCENT, edgecolor="#1e3a8a", linewidth=0.6, alpha=0.85)
    ax.axvline(0, color=_MUTED, linewidth=1.2, linestyle="--")
    ax.set_xlabel("Residual (log scale)")
    ax.set_ylabel("Count")
    ax.set_title("Residual distribution (log scale)")
    _save_fixed(fig, chart_dir / "residual_distribution.png")

    fig, ax = _new_axes()
    bins_x = [r["mean_predicted"] for r in calib_rows]
    bins_pred = [r["mean_predicted"] for r in calib_rows]
    bins_actual = [r["mean_actual"] for r in calib_rows]
    ax.plot(bins_x, bins_pred, marker="o", color=_ACCENT, linewidth=2, label="mean predicted")
    ax.plot(bins_x, bins_actual, marker="s", color=_MUTED, linewidth=2, label="mean actual")
    ax.legend(loc="upper left")
    ax.set_xlabel("Bin (ordered by predicted xg)")
    ax.set_ylabel("xg")
    ax.set_title("Calibration: mean predicted vs mean actual xg, by bin")
    _save_fixed(fig, chart_dir / "calibration_bins.png")

    fig, ax = _new_axes()
    if coef_table is not None and len(coef_table) > 0:
        top = coef_table.reindex(coef_table["abs_coef"].sort_values(ascending=False).index)[:15]
        ax.barh(top["feature"][::-1], top["coef"][::-1], color=_ACCENT)
        ax.set_xlabel("Coefficient (log-xg scale)")
        ax.set_title("Top 15 |coefficient|")
    else:
        ax.text(0.5, 0.5, "No features (dummy variant)", ha="center", va="center", transform=ax.transAxes, color=_MUTED)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_title("Feature coefficients (n/a)")
    _save_fixed(fig, chart_dir / "feature_coefficients.png")


# ---------------------------------------------------------------------------
# Classifier scoring (reuse only, never refit)
# ---------------------------------------------------------------------------

def score_classifier(trainval_full_df: pd.DataFrame, target_df: pd.DataFrame) -> np.ndarray:
    if not CLASSIFIER_JOBLIB.exists():
        raise FileNotFoundError(
            f"Expected promoted classifier artifact not found at {CLASSIFIER_JOBLIB}. "
            "This script's whole premise depends on reusing a real, already-validated artifact -- "
            "stopping rather than silently retraining it."
        )
    builder = p1d_mod.RFDesignMatrixBuilder().fit(trainval_full_df)
    x, _ = builder.transform(target_df)
    model = joblib.load(CLASSIFIER_JOBLIB)
    return model.predict_proba(x)[:, 1]


def main() -> None:
    REG_DIR.mkdir(parents=True, exist_ok=True)
    REG_CHARTS_DIR.mkdir(parents=True, exist_ok=True)
    COMPARISONS_DIR.mkdir(parents=True, exist_ok=True)
    VALIDATION_DIR.mkdir(parents=True, exist_ok=True)

    print("[1/6] confirming inputs...")
    if not CLASSIFIER_JOBLIB.exists():
        raise FileNotFoundError(
            f"Expected promoted passive-binary classifier not found at {CLASSIFIER_JOBLIB} -- "
            "stopping rather than guessing or retraining it."
        )
    print(f"  classifier artifact confirmed: {CLASSIFIER_JOBLIB}")
    assert len(pb.ALL_FEATURE_COLS) == 38, f"Expected 38 locked PASSIVE features, got {len(pb.ALL_FEATURE_COLS)}"
    print(f"  38 locked PASSIVE features confirmed (4 categorical + 6 boolean + 26 continuous + 2 discrete)")

    df_all = pb.load_data()
    load_canonical_split()
    test_mask_full = canonical_test_mask(df_all, group_col=pb.GROUP_COL)
    trainval_full = df_all.loc[~test_mask_full].reset_index(drop=True)
    test_full = df_all.loc[test_mask_full].reset_index(drop=True)

    pos_all = df_all[df_all[pb.TARGET_COL] == 1].reset_index(drop=True)
    print(f"  positive rows (target_future_shot_10s==1): {len(pos_all)} of {len(df_all)}; "
          f"unique events: {pos_all[EVENT_COL].nunique()}")
    print(f"  positive rows with xg>1: {int((pos_all[TARGET_XG_COL] > 1).sum())}; xg<=0: {int((pos_all[TARGET_XG_COL] <= 0).sum())}")
    multi_xg_events = pos_all.groupby(EVENT_COL)[TARGET_XG_COL].nunique()
    print(f"  events with >1 distinct target_future_xg_10s value (should be 0): {int((multi_xg_events > 1).sum())}")

    pos_test_mask = canonical_test_mask(pos_all, group_col=pb.GROUP_COL)
    pos_trainval = pos_all.loc[~pos_test_mask].reset_index(drop=True)
    pos_test = pos_all.loc[pos_test_mask].reset_index(drop=True)
    print(f"  positive trainval rows: {len(pos_trainval)} ({pos_trainval[pb.GROUP_COL].nunique()} matches, "
          f"{pos_trainval[EVENT_COL].nunique()} unique events); "
          f"positive held-out test rows: {len(pos_test)} ({pos_test[pb.GROUP_COL].nunique()} matches, "
          f"{pos_test[EVENT_COL].nunique()} unique events)")

    fold_probe = canonical_grouped_folds(pos_trainval, group_col=pb.GROUP_COL)
    probe_df = pos_trainval.loc[fold_probe["row_index"]].copy()
    probe_df["fold"] = fold_probe["fold"].to_numpy()
    fold_row_counts = probe_df.groupby("fold").size()
    fold_event_counts = probe_df.groupby("fold")[EVENT_COL].nunique()
    print(f"  positive rows per canonical fold: {fold_row_counts.to_dict()}")
    print(f"  unique events per canonical fold: {fold_event_counts.to_dict()}")
    thin_event_folds = fold_event_counts[fold_event_counts < 100]
    if len(thin_event_folds) > 0:
        print(f"  [FLAG] thin fold(s) by EVENT count (<100 unique events): {thin_event_folds.to_dict()} -- "
              "CV metrics on these folds should be read cautiously, even though row counts are large")
    else:
        print("  no fold has fewer than 100 unique events -- CV metrics rest on a reasonably stable "
              "effective sample size, not just a large row count")

    print("\n[2/6] cross-validation, d0_dummy and d1_lognormal_glm...")
    comparison_rows = []
    cv_results = {}
    for variant in VARIANTS:
        print(f"  [cv] {variant}")
        result = run_cv_regression(pos_trainval, variant)
        cv_results[variant] = result
        row = {"variant": variant, "n_features": 0 if variant == "d0_dummy" else 38}
        row.update(result["oof_metrics"])
        row["rows"] = len(pos_trainval)
        row["matches"] = pos_trainval[pb.GROUP_COL].nunique()
        row["events"] = pos_trainval[EVENT_COL].nunique()
        comparison_rows.append(row)

    print("\n[3/6] significance test, d1 vs d0 (common-scale natural-log(xg) RMSE per fold)...")
    fold_common_log_rmse = {v: cv_results[v]["fold_metrics"]["common_log_rmse"].tolist() for v in VARIANTS}
    fold_native_log_rmse = {v: cv_results[v]["fold_metrics"]["log_rmse"].tolist() for v in VARIANTS}
    fold_events = cv_results["d1_lognormal_glm"]["fold_metrics"][["fold", "n_test", "n_test_events"]].to_dict(orient="records")
    a = np.array(fold_common_log_rmse["d1_lognormal_glm"])
    b = np.array(fold_common_log_rmse["d0_dummy"])
    diff = a - b
    t_stat, p_val = stats.ttest_rel(a, b)
    if len(set(diff.round(12))) > 1:
        w_stat, w_p = stats.wilcoxon(a, b)
    else:
        w_stat, w_p = float("nan"), float("nan")
    min_test_events = min(r["n_test_events"] for r in fold_events)
    sig = {
        "metric": "common_log_rmse (per fold, natural-log(xg) scale for both variants, lower is better)",
        "scale_mismatch_note": (
            "d0_dummy is fit and natively evaluated on log1p(xg), d1_lognormal_glm on log(xg) -- "
            "not directly comparable numbers. common_log_rmse (natural log of both variants' "
            "xg-scale predictions) is used instead, for a fair head-to-head comparison, same fix "
            "Prompt 54 introduced on the active leg."
        ),
        "fold_common_log_rmse": fold_common_log_rmse,
        "fold_native_log_rmse": fold_native_log_rmse,
        "fold_test_rows_and_events": fold_events,
        "mean_diff_d1_minus_d0": float(diff.mean()),
        "std_diff": float(diff.std(ddof=1)),
        "paired_t_stat": float(t_stat),
        "paired_t_pvalue": float(p_val),
        "wilcoxon_stat": float(w_stat) if w_stat == w_stat else None,
        "wilcoxon_pvalue": float(w_p) if w_p == w_p else None,
        "n_folds": int(len(a)),
        "effective_sample_size_note": (
            f"This leg's per-fold ROW count (thousands) is much larger than the active leg's "
            f"(hundreds), but the effective sample size for this significance test is closer to the "
            f"per-fold EVENT count (minimum across folds: {min_test_events} unique events), since "
            "every defender-slot row sharing an event_id carries the identical target value -- "
            "rows are not independent observations of different outcomes. The test's row-count-implied "
            "power should NOT be read at face value; read it as informed by the event count instead. "
            "That said, even the thinnest fold's event count here is well above the active leg's own "
            "per-fold row counts (hundreds), so this is a real, meaningfully-sized test -- just not as "
            "large as the raw row count alone would suggest."
        ),
    }
    (VALIDATION_DIR / "significance_d0_vs_d1.json").write_text(json.dumps(sig, indent=2), encoding="utf-8")
    print(f"  mean_diff (d1-d0) common_log_rmse: {sig['mean_diff_d1_minus_d0']:+.4f}, "
          f"paired_t_p={sig['paired_t_pvalue']:.4f}, wilcoxon_p={sig['wilcoxon_pvalue']}")
    print(f"  min per-fold test-event count: {min_test_events}")

    print("\n[4/6] held-out test readout (fit once on all positive trainval rows)...")
    held_out_rows = []
    final_models = {}
    for variant in VARIANTS:
        log_pred, sigma2, model, extra = fit_predict_regression(pos_trainval, pos_test, variant)
        final_models[variant] = (model, extra, sigma2)

        y_true_log = np.log1p(pos_test[TARGET_XG_COL].to_numpy()) if variant == "d0_dummy" else np.log(pos_test[TARGET_XG_COL].to_numpy())
        y_true_xg = pos_test[TARGET_XG_COL].to_numpy()
        log_resid = log_pred - y_true_log

        xg_naive = np.expm1(log_pred) if variant == "d0_dummy" else backtransform(log_pred, sigma2, "naive")
        xg_corrected = xg_naive if variant == "d0_dummy" else backtransform(log_pred, sigma2, "lognormal_corrected")
        common_log_resid = np.log(xg_naive) - np.log(y_true_xg)

        row = {"variant": variant, "readout": "FINAL_HELD_OUT_TEST_NOT_FOR_SELECTION",
               "rows": len(pos_test), "matches": pos_test[pb.GROUP_COL].nunique(),
               "events": pos_test[EVENT_COL].nunique(),
               "log_rmse": float(np.sqrt(np.mean(log_resid ** 2))), "log_mae": float(np.mean(np.abs(log_resid))),
               "common_log_rmse": float(np.sqrt(np.mean(common_log_resid ** 2))),
               "common_log_mae": float(np.mean(np.abs(common_log_resid)))}
        row.update({f"naive_{k}": v for k, v in regression_metrics(y_true_xg, xg_naive).items()})
        row.update({f"corrected_{k}": v for k, v in regression_metrics(y_true_xg, xg_corrected).items()})
        held_out_rows.append(row)

        calib_variant_pred = xg_corrected if variant != "d0_dummy" else xg_naive
        calib_rows = calibration_bins(y_true_xg, calib_variant_pred)

        coef_table = None
        if variant == "d1_lognormal_glm":
            builder, feature_names = extra
            coefs = model.coef_
            coef_table = pd.DataFrame({
                "feature": feature_names, "coef": coefs, "abs_coef": np.abs(coefs),
            }).sort_values("abs_coef", ascending=False).reset_index(drop=True)
            coeff_json = {
                "variant": variant, "intercept": float(model.intercept_),
                "n_features": len(feature_names),
                "coefficients": coef_table.to_dict(orient="records"),
                "fitted_on": "all positive-row train+val rows (canonical split); held-out test used once for readout only",
            }
            (REG_DIR / f"{variant}.json").write_text(json.dumps(coeff_json, indent=2), encoding="utf-8")

        save_regression_variant_charts(
            REG_CHARTS_DIR / variant, y_true_log, log_pred, y_true_xg, calib_variant_pred, calib_rows, coef_table
        )
        joblib.dump(model, REG_DIR / f"{variant}.joblib")
        print(f"  [held-out] {variant}: log_rmse={row['log_rmse']:.4f} naive_mae={row['naive_mae']:.4f} "
              f"corrected_mae={row['corrected_mae']:.4f} naive_r2={row['naive_r2']:.4f} corrected_r2={row['corrected_r2']:.4f}")

    print("\n[5/6] writing comparison CSVs...")
    append_to_csv(COMPARISONS_DIR / "passive_continuous_baseline_comparison.csv", comparison_rows)
    append_to_csv(COMPARISONS_DIR / "passive_continuous_baseline_held_out_test_readout.csv", held_out_rows)

    print("\n[6/6] full hurdle pipeline readout (diagnostic, not the Rung-0 gate)...")
    # Row-grain check: the classifier's own training data is passive_defense.parquet at the
    # SAME defender-slot grain as this regression's target_df -- confirmed by construction
    # (both load via pb.load_data() / p1d_mod's RFDesignMatrixBuilder on the same df), not
    # assumed. No collapsing across defender-slots needed or performed.
    assert len(test_full) == len(df_all.loc[test_mask_full]), "held-out row grain mismatch"
    d1_model, d1_extra, d1_sigma2 = final_models["d1_lognormal_glm"]
    d1_builder, d1_feature_names = d1_extra
    x_full_test, _ = d1_builder.transform(test_full)
    log_pred_full = d1_model.predict(x_full_test)
    e_xg_given_shot = backtransform(log_pred_full, d1_sigma2, "lognormal_corrected")

    p_shot_full_test = score_classifier(trainval_full, test_full)
    assert len(p_shot_full_test) == len(test_full), "P(shot) row grain mismatch vs E[xg|shot] row grain"

    combined_pred = p_shot_full_test * e_xg_given_shot
    hurdle_oof = pd.DataFrame({
        "observed_future_xg": test_full[TARGET_XG_COL].to_numpy(),
        "combined_future_xg_prediction": combined_pred,
        "match_id": test_full[pb.GROUP_COL].to_numpy(),
    })
    hurdle_metrics = compute_hurdle_metrics(hurdle_oof, prediction_col="combined_future_xg_prediction")

    trivial_mean = float(trainval_full[TARGET_XG_COL].mean())
    trivial_pred = np.full(len(test_full), trivial_mean)
    trivial_oof = pd.DataFrame({
        "observed_future_xg": test_full[TARGET_XG_COL].to_numpy(),
        "trivial_prediction": trivial_pred,
        "match_id": test_full[pb.GROUP_COL].to_numpy(),
    })
    trivial_metrics = compute_hurdle_metrics(trivial_oof, prediction_col="trivial_prediction")

    hurdle_readout = {
        "held_out_test_rows": len(test_full),
        "held_out_test_matches": int(test_full[pb.GROUP_COL].nunique()),
        "held_out_test_events": int(test_full[EVENT_COL].nunique()),
        "row_grain_note": (
            "Held-out test rows are at the same defender-slot-per-event grain as the classifier's "
            "own training data and this regression's own positive-row subset -- confirmed by "
            "construction (same passive_defense.parquet, same row index), not collapsed across "
            "defender-slots for this readout."
        ),
        "classifier_variant": CLASSIFIER_VARIANT,
        "regression_variant": "d1_lognormal_glm (lognormal_corrected back-transform)",
        "hurdle_pipeline_metrics": hurdle_metrics,
        "trivial_unconditional_mean_baseline": trivial_mean,
        "trivial_baseline_metrics": trivial_metrics,
        "note": (
            "Diagnostic readout only -- not the Rung-0 gate. Rung-0 promotion is decided by the "
            "regression-only d1-vs-d0 comparison (significance_d0_vs_d1.json), not by this end-to-end "
            "hurdle number."
        ),
    }
    (VALIDATION_DIR / "hurdle_pipeline_readout_passive.json").write_text(json.dumps(hurdle_readout, indent=2), encoding="utf-8")
    print(f"  hurdle pipeline: rmse={hurdle_metrics['rmse']:.5f} mae={hurdle_metrics['mae']:.5f} r2={hurdle_metrics['r2']:.5f}")
    print(f"  trivial baseline: rmse={trivial_metrics['rmse']:.5f} mae={trivial_metrics['mae']:.5f} r2={trivial_metrics['r2']:.5f}")

    print("\n=== CV comparison (5-fold, OOF metrics; common_log_rmse is the fair cross-variant comparison) ===")
    print(pd.DataFrame(comparison_rows)[["variant", "common_log_rmse", "common_log_mae", "naive_mae", "corrected_mae", "naive_r2", "corrected_r2"]].to_string(index=False))
    print("\n=== Held-out test readout ===")
    print(pd.DataFrame(held_out_rows)[["variant", "common_log_rmse", "naive_mae", "corrected_mae", "naive_r2", "corrected_r2"]].to_string(index=False))
    print("\nDone.")


if __name__ == "__main__":
    main()
